### PR TITLE
Fix PR for entrypoint.sh script

### PR DESCRIPTION
**Pull request by deed02392**

### CODE REVIEW

**Comment by deed02392** [comment]
Closes #11

**Comment by JackDandy** [comment]
This PR is wrong as it has not been created on the current head of develop which is why it is 6 commits long... it's supposed to be only one commit with the *exec* change(s) as all the other commits here have been squashed and merged already. 

Also, there are two instances of **exec gosu** in the script, @ressu can you confirm what needs to be changed for this fix.

Thanks.

**Comment by ressu** [comment]
The change looks good. There are supposed to be 2 exit points for the script. One forcibly executes SickBeard.py and the other executes the user given command.

**Comment by JackDandy** [comment]
thanks @ressu i'll cherry pick the fix to clean this up.

Merged and closing this PR as it is now redundant..

I'm not sure if any of this applies to branch master @ressu that's in your expertise of knowledge ;)

**Comment by deed02392** [comment]
Ah, I should have rebased my tree on the new head of develop or something?

**Pull request closed without merging**
