### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by herkalurk**
change watchtower image to official watch tower, add example of docker compose file

### CODE REVIEW

**Comment by herkalurk** [comment]
Proposed based on previous comments...

https://github.com/SickGear/SickGear.Docker/issues/36

**Comment by JackDandy** [comment]
Looking good, can you change the default  TZ to UTC

**Comment by herkalurk** [comment]
Updated, I only replicated what you had originally in the docker run example.

**Comment by JackDandy** [comment]
> Updated, I only replicated what you had originally in the docker run example

Yeah, had I have noticed before, then I would have asked the original contributor. Okay, I will neaten up and flatten this PR for a cleaner release.

And thanks for the PR :)

**Comment by JackDandy** [comment]
Hi @herkalurk 

Can you do a favour and confirm if the original docker run example is missing a newline `\` character (nothing to do with you, it's always been there, as a windows user, I may be mistaken), the section reads...

**START**
...need to add a `--name <containername>` to the run command. For example:
```
docker run \
  --name sickgear
  -v /storage/incoming:/incoming \
  -v /storage/tv:/tv \
  -v /storage/sickgear-data:/data \
  -p 8081:8081 ressu/sickgear
```
**END**

and I think it should read....

**START**
...need to add a `--name <containername>` to the run command. For example:
```
docker run \
  --name sickgear \
  -v /storage/incoming:/incoming \
  -v /storage/tv:/tv \
  -v /storage/sickgear-data:/data \
  -p 8081:8081 ressu/sickgear
```
**END**

adding `\` after the `--name` parameter, but I cannot test as I don't use this docker setup.

Thanks for your assist.

**Comment by herkalurk** [comment]
Yes, it should have one, but the new line this is more for making this pretty.  Both of the below code will run the same, some people like to include the escape characters `\` so they can keep the lines of code shorter so people reading it don't have to scroll left or right.  I find some people use this too frequently on things that would never cause users to scroll to one side or the other.

```
docker run --name sickgear -v /storage/incoming:/incoming -v /storage/tv:/tv -v /storage/sickgear-data:/data -p 8081:8081 ressu/sickgear
```

```
docker run \
  --name sickgear \
  -v /storage/incoming:/incoming \
  -v /storage/tv:/tv \
  -v /storage/sickgear-data:/data \
  -p 8081:8081 ressu/sickgear
```

**Pull request closed without merging**
